version: "3.8"

services:
  dms:
    image: wiramin/dms:latest
    container_name: dms
    ports:
      - "5290:5290"
      - "5291:5291"
    volumes:
      - ./DocumentManagementSystemApplication/data:/app/data
    restart: unless-stopped