version: "3.8"

services:
  dms:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dms
    ports:
      - "5290:5290"
      - "5291:5291"
    volumes:
      - ./DocumentManagementSystemApplication/data:/app/data
    env_file:
      - ./.env
    networks:
      - dmsBe
    restart: unless-stopped
    
  ai:
    image: ambrose47/ocr-flask-app:latest
    container_name: aiDms
    ports:
      - "5000:5000"
    networks:
      - dmsBe
networks:
  dmsBe:
    driver: bridge