version: '3.8'

services:
#  document_management_system:
#    image: wiramin/dmsbe:latest
#    ports:
#      - "8080:5290"
#      - "8081:5291"
#    environment:
#      ASPNETCORE_ENVIRONMENT: Development
##      ASPNETCORE_URLS: "http://+:8080;https://+:8443"
#      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
#      ASPNETCORE_Kestrel__Certificates__Default__Password: "ambrosezen"
#    volumes:
#      - ./https:/https:ro
#      - ./doc:/doc
#      - ./arDoc:/arDoc
#    networks:
#      - dmsNet
  redis:
    container_name: redis_dms
    image: redis:8.0-M04-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
    networks:
      - dmsNet
  elasticsearch:
    container_name: elasticsearch_dms
    image: elasticsearch:8.17.4
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enable=false
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data
    networks:
      - dmsNet
  kibana:
    container_name: kibana_dms
    image: kibana:8.17.4
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - dmsNet
networks:
  dmsNet:
    driver: bridge
