version: '3.8'

services:
  document_management_system:
    build: .
    ports:
      - "8082:8080"
      - "8443:8443"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:8080;https://+:8443"
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: "ambrosezen"
    volumes:
      - ./https:/https:ro
