version: "3.8"

services:
  dms:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dms
#    environment:
#      - TZ=Asia/Ho_Chi_Minh        
    ports:
      - "5290:5290"  # Chỉ giữ cổng 5290
    volumes:
      - ./DocumentManagementSystemApplication/data:/app/data
#      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ./.env
    networks:
      - app-network
    restart: unless-stopped

  ai:
    image: ambrose47/ocr-flask-app:latest
    container_name: aiDms
    ports:
      - "5000:5000"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    external: true
