// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(DocumentManagementSystemDbContext))]
    [Migration("20250331062835_UpdateDataBaseVersion3_Update_Doc_Status_WF")]
    partial class UpdateDataBaseVersion3_Update_Doc_Status_WF
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BusinessObject.ArchiveDocumentSignature", b =>
                {
                    b.Property<Guid>("ArchiveDocumentSignatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ArchivedDocumentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DigitalCertificateId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("SignatureValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ArchiveDocumentSignatureId");

                    b.HasIndex("ArchivedDocumentId");

                    b.HasIndex("DigitalCertificateId");

                    b.ToTable("ArchiveDocumentSignature", (string)null);
                });

            modelBuilder.Entity("BusinessObject.ArchivedDocument", b =>
                {
                    b.Property<Guid>("ArchivedDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ArchivedDocumentContent")
                        .HasColumnType("text");

                    b.Property<string>("ArchivedDocumentName")
                        .HasColumnType("text");

                    b.Property<int>("ArchivedDocumentStatus")
                        .HasColumnType("integer");

                    b.Property<string>("ArchivedDocumentUrl")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateIssued")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateReceived")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateSented")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DocumentReplaceId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DocumentRevokeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalPartner")
                        .HasColumnType("text");

                    b.Property<Guid>("FinalDocumentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsTemplate")
                        .HasColumnType("boolean");

                    b.Property<string>("NumberOfDocument")
                        .HasColumnType("text");

                    b.Property<int>("Scope")
                        .HasColumnType("integer");

                    b.Property<string>("Sender")
                        .HasColumnType("text");

                    b.Property<string>("SignedBy")
                        .HasColumnType("text");

                    b.HasKey("ArchivedDocumentId");

                    b.HasIndex("DocumentReplaceId");

                    b.HasIndex("DocumentRevokeId");

                    b.HasIndex("DocumentTypeId");

                    b.ToTable("ArchivedDocument", (string)null);
                });

            modelBuilder.Entity("BusinessObject.AttachmentArchivedDocument", b =>
                {
                    b.Property<Guid>("AttachmentArchivedDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ArchivedDocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("AttachmentName")
                        .HasColumnType("text");

                    b.Property<string>("AttachmentUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("AttachmentArchivedDocumentId");

                    b.HasIndex("ArchivedDocumentId");

                    b.ToTable("AttachmentArchivedDocument", (string)null);
                });

            modelBuilder.Entity("BusinessObject.AttachmentDocument", b =>
                {
                    b.Property<Guid>("AttachmentDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AttachmentDocumentName")
                        .HasColumnType("text");

                    b.Property<string>("AttachmentDocumentUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("AttachmentDocumentId");

                    b.HasIndex("DocumentId");

                    b.ToTable("AttachmentDocument", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Comment", b =>
                {
                    b.Property<Guid>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CommentContent")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("CommentId");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId");

                    b.ToTable("Comment", (string)null);
                });

            modelBuilder.Entity("BusinessObject.DigitalCertificate", b =>
                {
                    b.Property<Guid>("DigitalCertificateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("HashAlgorithm")
                        .HasColumnType("text");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Issuer")
                        .HasColumnType("text");

                    b.Property<string>("OwnerName")
                        .HasColumnType("text");

                    b.Property<string>("PublicKey")
                        .HasColumnType("text");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text");

                    b.Property<string>("SignatureImageUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DigitalCertificateId");

                    b.HasIndex("UserId");

                    b.ToTable("DigitalCertificate", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Division", b =>
                {
                    b.Property<Guid>("DivisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("DivisionName")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("DivisionId");

                    b.ToTable("Division", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Document", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DateIssued")
                        .HasColumnType("text");

                    b.Property<string>("DateReceived")
                        .HasColumnType("text");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentContent")
                        .HasColumnType("text");

                    b.Property<string>("DocumentName")
                        .HasColumnType("text");

                    b.Property<int>("DocumentPriority")
                        .HasColumnType("integer");

                    b.Property<Guid?>("DocumentTypeWorkflowId")
                        .HasColumnType("uuid");

                    b.Property<string>("DocumentUrl")
                        .HasColumnType("text");

                    b.Property<Guid?>("FinalArchiveDocumentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("NumberOfDocument")
                        .HasColumnType("text");

                    b.Property<int>("ProcessingStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Sender")
                        .HasColumnType("text");

                    b.Property<string>("SignedBy")
                        .HasColumnType("text");

                    b.Property<Guid?>("TemplateArchiveDocumentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("DocumentId");

                    b.HasIndex("DocumentTypeWorkflowId");

                    b.HasIndex("FinalArchiveDocumentId")
                        .IsUnique();

                    b.HasIndex("TemplateArchiveDocumentId");

                    b.HasIndex("UserId");

                    b.ToTable("Document", (string)null);
                });

            modelBuilder.Entity("BusinessObject.DocumentSignature", b =>
                {
                    b.Property<Guid>("DocumentSignatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("DigitalCertificateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("SignatureValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DocumentSignatureId");

                    b.HasIndex("DigitalCertificateId");

                    b.HasIndex("DocumentId");

                    b.ToTable("DocumentSignature", (string)null);
                });

            modelBuilder.Entity("BusinessObject.DocumentType", b =>
                {
                    b.Property<Guid>("DocumentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("DocumentTypeName")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("DocumentTypeId");

                    b.ToTable("DocumentType", (string)null);
                });

            modelBuilder.Entity("BusinessObject.DocumentTypeWorkflow", b =>
                {
                    b.Property<Guid>("DocumentTypeWorkflowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("DocumentTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.HasKey("DocumentTypeWorkflowId");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("WorkflowId");

                    b.ToTable("DocumentTypeWorkflow", (string)null);
                });

            modelBuilder.Entity("BusinessObject.DocumentVersion", b =>
                {
                    b.Property<Guid>("DocumentVersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("DocumentVersionUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsFinalVersion")
                        .HasColumnType("boolean");

                    b.Property<string>("VersionNumber")
                        .HasColumnType("text");

                    b.HasKey("DocumentVersionId");

                    b.HasIndex("DocumentId");

                    b.ToTable("DocumentVersion", (string)null);
                });

            modelBuilder.Entity("BusinessObject.DocumentWorkflowStatus", b =>
                {
                    b.Property<Guid>("DocumentWorkflowStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CurrentWorkflowFlowId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<int>("StatusDoc")
                        .HasColumnType("integer");

                    b.Property<int>("StatusDocWorkflow")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.HasKey("DocumentWorkflowStatusId");

                    b.HasIndex("CurrentWorkflowFlowId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("WorkflowId");

                    b.ToTable("DocumentWorkflowStatus", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Flow", b =>
                {
                    b.Property<Guid>("FlowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("RoleEnd")
                        .HasColumnType("text");

                    b.Property<string>("RoleStart")
                        .HasColumnType("text");

                    b.HasKey("FlowId");

                    b.ToTable("Flow", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Permission", b =>
                {
                    b.Property<Guid>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("PermissionName")
                        .HasColumnType("text");

                    b.HasKey("PermissionId");

                    b.ToTable("Permission", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Resource", b =>
                {
                    b.Property<Guid>("ResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResourceApi")
                        .HasColumnType("text");

                    b.Property<string>("ResourceName")
                        .HasColumnType("text");

                    b.HasKey("ResourceId");

                    b.HasIndex("PermissionId");

                    b.ToTable("Resource", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("RoleName")
                        .HasColumnType("text");

                    b.HasKey("RoleId");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("BusinessObject.RoleResource", b =>
                {
                    b.Property<Guid>("RoleResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("RoleResourceId");

                    b.HasIndex("ResourceId");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleResource", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Step", b =>
                {
                    b.Property<Guid>("StepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Action")
                        .HasColumnType("text");

                    b.Property<Guid>("FlowId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("NextStepId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<int>("StepNumber")
                        .HasColumnType("integer");

                    b.HasKey("StepId");

                    b.HasIndex("FlowId");

                    b.HasIndex("RoleId");

                    b.ToTable("Step", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Task", b =>
                {
                    b.Property<Guid>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StepId")
                        .HasColumnType("uuid");

                    b.Property<int>("TaskStatus")
                        .HasColumnType("integer");

                    b.Property<int>("TaskType")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("TaskId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("StepId");

                    b.HasIndex("UserId");

                    b.ToTable("Task", (string)null);
                });

            modelBuilder.Entity("BusinessObject.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DivisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FcmToken")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("IdentityCard")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEnable")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("DivisionId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("BusinessObject.UserDocumentPermission", b =>
                {
                    b.Property<Guid>("UserDocumentPermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ArchivedDocumentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("UserDocumentPermissionId");

                    b.HasIndex("ArchivedDocumentId");

                    b.HasIndex("UserId");

                    b.ToTable("UserDocumentPermission", (string)null);
                });

            modelBuilder.Entity("BusinessObject.UserRole", b =>
                {
                    b.Property<Guid>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("UserRoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRole", (string)null);
                });

            modelBuilder.Entity("BusinessObject.VerificationOtp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTrue")
                        .HasColumnType("boolean");

                    b.Property<string>("Otp")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("VerificationOtp", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Workflow", b =>
                {
                    b.Property<Guid>("WorkflowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("IsAllocate")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Scope")
                        .HasColumnType("integer");

                    b.Property<string>("WorkflowName")
                        .HasColumnType("text");

                    b.HasKey("WorkflowId");

                    b.ToTable("Workflow", (string)null);
                });

            modelBuilder.Entity("BusinessObject.WorkflowFlow", b =>
                {
                    b.Property<Guid>("WorkflowFlowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("FlowId")
                        .HasColumnType("uuid");

                    b.Property<bool>("FlowNumber")
                        .HasColumnType("boolean");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.HasKey("WorkflowFlowId");

                    b.HasIndex("FlowId");

                    b.HasIndex("WorkflowId");

                    b.ToTable("WorkflowFlow", (string)null);
                });

            modelBuilder.Entity("BusinessObject.WorkflowFlowTransition", b =>
                {
                    b.Property<Guid>("WorkflowFlowTransitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Condition")
                        .HasColumnType("integer");

                    b.Property<Guid>("CurrentWorkFlowFlowId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("NextWorkFlowFlowId")
                        .HasColumnType("uuid");

                    b.HasKey("WorkflowFlowTransitionId");

                    b.HasIndex("CurrentWorkFlowFlowId");

                    b.HasIndex("NextWorkFlowFlowId");

                    b.ToTable("WorkflowFlowTransition", (string)null);
                });

            modelBuilder.Entity("BusinessObject.ArchiveDocumentSignature", b =>
                {
                    b.HasOne("BusinessObject.ArchivedDocument", "ArchivedDocument")
                        .WithMany("ArchiveDocumentSignatures")
                        .HasForeignKey("ArchivedDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.DigitalCertificate", "DigitalCertificate")
                        .WithMany("ArchiveDocumentSignatures")
                        .HasForeignKey("DigitalCertificateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArchivedDocument");

                    b.Navigation("DigitalCertificate");
                });

            modelBuilder.Entity("BusinessObject.ArchivedDocument", b =>
                {
                    b.HasOne("BusinessObject.ArchivedDocument", null)
                        .WithMany("DocumentRevokes")
                        .HasForeignKey("DocumentReplaceId");

                    b.HasOne("BusinessObject.ArchivedDocument", null)
                        .WithMany("DocumentReplaces")
                        .HasForeignKey("DocumentRevokeId");

                    b.HasOne("BusinessObject.DocumentType", "DocumentType")
                        .WithMany("ArchivedDocuments")
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentType");
                });

            modelBuilder.Entity("BusinessObject.AttachmentArchivedDocument", b =>
                {
                    b.HasOne("BusinessObject.ArchivedDocument", "ArchivedDocument")
                        .WithMany("AttachmentArchivedDocuments")
                        .HasForeignKey("ArchivedDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArchivedDocument");
                });

            modelBuilder.Entity("BusinessObject.AttachmentDocument", b =>
                {
                    b.HasOne("BusinessObject.Document", "Document")
                        .WithMany("AttachmentDocuments")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("BusinessObject.Comment", b =>
                {
                    b.HasOne("BusinessObject.Task", "Task")
                        .WithMany("Comments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObject.DigitalCertificate", b =>
                {
                    b.HasOne("BusinessObject.User", "User")
                        .WithMany("DigitalCertificates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObject.Document", b =>
                {
                    b.HasOne("BusinessObject.DocumentTypeWorkflow", "DocumentTypeWorkflow")
                        .WithMany("Documents")
                        .HasForeignKey("DocumentTypeWorkflowId");

                    b.HasOne("BusinessObject.ArchivedDocument", "FinalArchiveDocument")
                        .WithOne("FinalDocument")
                        .HasForeignKey("BusinessObject.Document", "FinalArchiveDocumentId");

                    b.HasOne("BusinessObject.ArchivedDocument", "TemplateArchiveDocument")
                        .WithMany("CreateDocuments")
                        .HasForeignKey("TemplateArchiveDocumentId");

                    b.HasOne("BusinessObject.User", "User")
                        .WithMany("Documents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentTypeWorkflow");

                    b.Navigation("FinalArchiveDocument");

                    b.Navigation("TemplateArchiveDocument");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObject.DocumentSignature", b =>
                {
                    b.HasOne("BusinessObject.DigitalCertificate", "DigitalCertificate")
                        .WithMany("DocumentSignatures")
                        .HasForeignKey("DigitalCertificateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Document", "Document")
                        .WithMany("DocumentSignatures")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DigitalCertificate");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("BusinessObject.DocumentTypeWorkflow", b =>
                {
                    b.HasOne("BusinessObject.DocumentType", "DocumentType")
                        .WithMany("DocumentTypeWorkflows")
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Workflow", "Workflow")
                        .WithMany("DocumentTypeWorkflows")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentType");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("BusinessObject.DocumentVersion", b =>
                {
                    b.HasOne("BusinessObject.Document", "Document")
                        .WithMany("DocumentVersions")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("BusinessObject.DocumentWorkflowStatus", b =>
                {
                    b.HasOne("BusinessObject.WorkflowFlow", "CurrentWorkflowFlow")
                        .WithMany("DocumentWorkflowStatuses")
                        .HasForeignKey("CurrentWorkflowFlowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Document", "Document")
                        .WithMany("DocumentWorkflowStatuses")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Workflow", "Workflow")
                        .WithMany("DocumentWorkflowStatuses")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentWorkflowFlow");

                    b.Navigation("Document");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("BusinessObject.Resource", b =>
                {
                    b.HasOne("BusinessObject.Permission", "Permission")
                        .WithMany("Resources")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("BusinessObject.RoleResource", b =>
                {
                    b.HasOne("BusinessObject.Resource", "Resource")
                        .WithMany("RoleResources")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Role", "Role")
                        .WithMany("RoleResources")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BusinessObject.Step", b =>
                {
                    b.HasOne("BusinessObject.Flow", "Flow")
                        .WithMany("Steps")
                        .HasForeignKey("FlowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Role", "Role")
                        .WithMany("Steps")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flow");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BusinessObject.Task", b =>
                {
                    b.HasOne("BusinessObject.Document", "Document")
                        .WithMany("Tasks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Step", "Step")
                        .WithMany("Tasks")
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.User", "User")
                        .WithMany("Tasks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Step");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObject.User", b =>
                {
                    b.HasOne("BusinessObject.Division", "Division")
                        .WithMany("Users")
                        .HasForeignKey("DivisionId");

                    b.Navigation("Division");
                });

            modelBuilder.Entity("BusinessObject.UserDocumentPermission", b =>
                {
                    b.HasOne("BusinessObject.ArchivedDocument", "ArchivedDocument")
                        .WithMany("UserDocumentPermissions")
                        .HasForeignKey("ArchivedDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.User", "User")
                        .WithMany("UserDocumentPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArchivedDocument");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObject.UserRole", b =>
                {
                    b.HasOne("BusinessObject.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObject.VerificationOtp", b =>
                {
                    b.HasOne("BusinessObject.User", "User")
                        .WithMany("VerificationOtps")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObject.WorkflowFlow", b =>
                {
                    b.HasOne("BusinessObject.Flow", "Flow")
                        .WithMany("WorkflowFlows")
                        .HasForeignKey("FlowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Workflow", "Workflow")
                        .WithMany("WorkflowFlows")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flow");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("BusinessObject.WorkflowFlowTransition", b =>
                {
                    b.HasOne("BusinessObject.WorkflowFlow", "CurrentWorkFlowFlow")
                        .WithMany("CurrentWorkflowFlowTransitions")
                        .HasForeignKey("CurrentWorkFlowFlowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.WorkflowFlow", "NextWorkFlowFlow")
                        .WithMany("NextWorkflowFlowTransitions")
                        .HasForeignKey("NextWorkFlowFlowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentWorkFlowFlow");

                    b.Navigation("NextWorkFlowFlow");
                });

            modelBuilder.Entity("BusinessObject.ArchivedDocument", b =>
                {
                    b.Navigation("ArchiveDocumentSignatures");

                    b.Navigation("AttachmentArchivedDocuments");

                    b.Navigation("CreateDocuments");

                    b.Navigation("DocumentReplaces");

                    b.Navigation("DocumentRevokes");

                    b.Navigation("FinalDocument");

                    b.Navigation("UserDocumentPermissions");
                });

            modelBuilder.Entity("BusinessObject.DigitalCertificate", b =>
                {
                    b.Navigation("ArchiveDocumentSignatures");

                    b.Navigation("DocumentSignatures");
                });

            modelBuilder.Entity("BusinessObject.Division", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BusinessObject.Document", b =>
                {
                    b.Navigation("AttachmentDocuments");

                    b.Navigation("DocumentSignatures");

                    b.Navigation("DocumentVersions");

                    b.Navigation("DocumentWorkflowStatuses");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("BusinessObject.DocumentType", b =>
                {
                    b.Navigation("ArchivedDocuments");

                    b.Navigation("DocumentTypeWorkflows");
                });

            modelBuilder.Entity("BusinessObject.DocumentTypeWorkflow", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("BusinessObject.Flow", b =>
                {
                    b.Navigation("Steps");

                    b.Navigation("WorkflowFlows");
                });

            modelBuilder.Entity("BusinessObject.Permission", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("BusinessObject.Resource", b =>
                {
                    b.Navigation("RoleResources");
                });

            modelBuilder.Entity("BusinessObject.Role", b =>
                {
                    b.Navigation("RoleResources");

                    b.Navigation("Steps");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("BusinessObject.Step", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("BusinessObject.Task", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("BusinessObject.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("DigitalCertificates");

                    b.Navigation("Documents");

                    b.Navigation("Tasks");

                    b.Navigation("UserDocumentPermissions");

                    b.Navigation("UserRoles");

                    b.Navigation("VerificationOtps");
                });

            modelBuilder.Entity("BusinessObject.Workflow", b =>
                {
                    b.Navigation("DocumentTypeWorkflows");

                    b.Navigation("DocumentWorkflowStatuses");

                    b.Navigation("WorkflowFlows");
                });

            modelBuilder.Entity("BusinessObject.WorkflowFlow", b =>
                {
                    b.Navigation("CurrentWorkflowFlowTransitions");

                    b.Navigation("DocumentWorkflowStatuses");

                    b.Navigation("NextWorkflowFlowTransitions");
                });
#pragma warning restore 612, 618
        }
    }
}
