name: Deploy .NET App to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH & Deploy
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_USERNAME: ${{ secrets.SERVER_USERNAME }}
          SSH_HOST: ${{ secrets.SERVER_HOST }}
          SSH_PORT: ${{ secrets.SERVER_PORT }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -p "$SSH_PORT" "$SSH_USERNAME@$SSH_HOST" << 'EOF'
            set -e
            echo "📥 Pulling latest code from Git..."
            cd /root/dms/Document_Management_System &&  git pull origin main || exit 1


           
            echo "🚀 build"
            docker-compose build --no-cache
            docker builder prune -f
            echo "🛑 Stopping old containers (if any)..."
            docker-compose down
            echo "🚀 Starting app..."
            docker-compose up -d --remove-orphans
          EOF
