name: Deploy .NET App to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH & Deploy
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_USERNAME: ${{ secrets.SERVER_USERNAME }}
          SSH_HOST: ${{ secrets.SERVER_HOST }}
          SSH_PORT: ${{ secrets.SERVER_PORT }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -p "$SERVER_PORT" -t "$SERVER_USERNAME@$SERVER_HOST" << 'EOF'
            set -e
            cd /root/dms/Document_Management_System &&  git pull origin main || exit 1


           
            docker compose build --no-cache
            docker compose down
            docker compose up -d --remove-orphans
          EOF
